version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: f1_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: f1_data
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - f1_network

  spark-master:
    image: apache/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - f1_network

  etl:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: devinluize12/formula1-ml-pipeline-etl:latest
    container_name: etl_service
    # command: ["./wait-for-postgres.sh", "f1_postgres", "python", "etl/etl_pipeline.py"]  # Already in Dockerfile CMD
    ports:
      - "8888:8888"  # For Jupyter or debugging
    depends_on:
      - postgres
      - spark-master
    networks:
      - f1_network

  dashboard:
#    build: ./dashboard
#      context: .
#      dockerfile: Dockerfile  # buat Dockerfile terpisah untuk dashboard
    image: devinluize12/formula1-ml-pipeline-dashboard
    container_name: f1_dashboard
    command: streamlit run dashboard/dashboard_app.py --server.port=8501
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - f1_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: f1_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - f1_network

networks:
  f1_network:
    driver: bridge