# version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: f1_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: f1_data
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - f1_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d f1_data -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  spark-master:
    build:
      context: ./pipelines/bigdata/spark
    container_name: spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    environment:
      SPARK_MODE: master
      SPARK_NO_DAEMONIZE: "true"
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT: 7077
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - f1_network
    restart: unless-stopped

  spark-worker-1:
    image: yenatari/formula1-ml-pipeline-spark-worker-1:latest
    container_name: spark-worker-1
    command:
      ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    environment:
      SPARK_MODE: worker
      SPARK_NO_DAEMONIZE: "true"
      SPARK_WORKER_CORES: "2"
      SPARK_WORKER_MEMORY: 4G
      SPARK_PUBLIC_DNS: spark-worker-1
      SPARK_WORKER_PORT: 8081
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    networks:
      - f1_network
    restart: unless-stopped

  spark-worker-2:
    image: yenatari/formula1-ml-pipeline-spark-worker-1:latest
    container_name: spark-worker-2
    command:
      ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    environment:
      SPARK_MODE: worker
      SPARK_NO_DAEMONIZE: "true"
      SPARK_WORKER_CORES: "2"
      SPARK_WORKER_MEMORY: 4G
      SPARK_PUBLIC_DNS: spark-worker-2
      SPARK_WORKER_PORT: 8082
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    volumes:
      - .:/app
    networks:
      - f1_network
    restart: unless-stopped

  etl:
    build:
      context: .
      dockerfile: Dockerfile
    # image: devinluize12/formula1-ml-pipeline-etl:latest
    container_name: etl_service
    # command: ["./wait-for-postgres.sh", "f1_postgres", "python", "etl/etl_pipeline.py"]  # Already in Dockerfile CMD
    ports:
      - "8888:8888"  # For Jupyter or debugging
    depends_on:
      - postgres
      - spark-master
    networks:
      - f1_network

  ml_train:
    build: 
      context: .
      dockerfile: ./ml/Dockerfile
    container_name: ml_train
    environment:
      - DB_HOST=f1_postgres
      - DB_NAME=f1_data
      - DB_USER=admin
      - DB_PASSWORD=admin123
    depends_on:
      - postgres
      - etl
    networks:
      - f1_network

  dashboard_classic:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: f1_dashboard_classic
    command: bash -c "python /app/docker/wait_for_table.py && streamlit run dashboard/classic_app.py --server.port=8501 --server.address=0.0.0.0"
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - f1_network

  dashboard_bigdata:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: f1_dashboard_bigdata
    command: bash -c "streamlit run dashboard/bigdata_app.py --server.port=8502 --server.address=0.0.0.0"
    ports:
      - "8502:8502"
    depends_on:
      - spark-master
    volumes:
      - .:/app
    networks:
      - f1_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: f1_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - f1_network

networks:
  f1_network:
    driver: bridge