# Dockerfile_dashboard
FROM python:3.11

# Set working directory
WORKDIR /app

# Install system dependencies (jika perlu, misal untuk postgres client)
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    g++ \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements dashboard
COPY dashboard/requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy seluruh project (atau hanya folder dashboard)
COPY . .

# Jalankan Streamlit dashboard
CMD ["streamlit", "run", "dashboard/dashboard_app.py", "--server.port=8501", "--server.address=0.0.0.0"]